const dbStudent = [
  {
    username: "John",
    fullname: "John Wick",
    password: "123456",
    class_level_id: 1,
    schoold_id: 1,
    address: "Jaksel",
    city_id: 1,
    province_id: 1,
    country_id: 1,
    postal_code_id: 1,
    hobby: "swimming",
    report_id: 1,
    class_organization_id: 1,
    osis: false,
    extracurricular_id: 1,
    pict: "google.com",
    phone_number: "0812123456",
    classroom_id: 1,
    email: "something@gmail.com",
    status: true
  },
  {
    username: "Brad",
    fullname: "Brad Pitt",
    password: "123456",
    class_level_id: 1,
    schoold_id: 1,
    address: "Jaksel",
    city_id: 1,
    province_id: 1,
    country_id: 1,
    postal_code_id: 1,
    hobby: "swimming",
    report_id: 1,
    class_organization_id: 1,
    osis: false,
    extracurricular_id: 1,
    pict: "google.com",
    phone_number: "0812123456",
    classroom_id: 1,
    email: "something@gmail.com",
    status: true
  },
  {
    username: "Nat",
    fullname: "Nat Murray",
    password: "123456",
    class_level_id: 1,
    schoold_id: 1,
    address: "Jaksel",
    city_id: 1,
    province_id: 1,
    country_id: 1,
    postal_code_id: 1,
    hobby: "swimming",
    report_id: 1,
    class_organization_id: 1,
    osis: false,
    extracurricular_id: 1,
    pict: "google.com",
    phone_number: "0812123456",
    classroom_id: 1,
    email: "something@gmail.com",
    status: true
  }
]

export default dbStudent