[
  {
    username: "John",
    fullname: "John Teacher",
    password: "123456",
    class_level_id: 1,
    schoold_id: 1,
    address: "Jaksel",
    city_id: 1,
    province_id: 1,
    country_id: 1,
    postal_code_id: 1,
    hobby: "swimming",
    extracurricular_conj: 1,
    report_id: 1,
    pict: "google.com",
    phone_number: "0812123456",
    school_id: 1,
    class_teacher_id: 1,
    email: "something@gmail.com",
    status: true
  },
  {
    username: "Brad",
    fullname: "Brad Teacher",
    password: "123456",
    class_level_id: 1,
    schoold_id: 1,
    address: "Jaksel",
    city_id: 1,
    province_id: 1,
    country_id: 1,
    postal_code_id: 1,
    hobby: "football",
    extracurricular_conj: 1,
    report_id: 1,
    pict: "google.com",
    phone_number: "08121234567",
    school_id: 1,
    class_teacher_id: 2,
    email: "something@gmail.com",
    status: true
  }
]